services:
    backend:
        build:
            context: ./backend
            dockerfile: docker/Dockerfile
        volumes:
            - ./backend:/var/www/html
            - ./backend/docker/php/php.ini:/usr/local/etc/php/php.ini
        env_file:
            - .env
        ports:
            - '8000:8000'
        networks:
            - zaplechnik_network
        depends_on:
            - postgis

    frontend:
        build:
            context: ./frontend
            dockerfile: Dockerfile
        ports:
            - "3000:3000"
        volumes:
            - ./frontend:/app
            - /app/node_modules
        networks:
            - zaplechnik_network

    postgis:
        image: 'postgis/postgis:17-3.5-alpine'
        ports:
            - '${FORWARD_DB_PORT:-5432}:5432'
        environment:
            PGPASSWORD: '${DB_PASSWORD:-secret}'
            POSTGRES_DB: '${DB_DATABASE}'
            POSTGRES_USER: '${DB_USERNAME}'
            POSTGRES_PASSWORD: '${DB_PASSWORD:-secret}'
        volumes:
            - 'pgsql_data:/var/lib/postgresql/data'
        networks:
            - zaplechnik_network

volumes:
    pgsql_data:
        driver: local

networks:
    zaplechnik_network:
        driver: bridge