services:
    backend:
        build:
            context: ./backend
            dockerfile: docker/Dockerfile
        volumes:
            - ./backend:/var/www/html
            - ./backend/docker/php/php.ini:/usr/local/etc/php/php.ini
        ports:
            - '8000:8000'
        networks:
            - zaplechnik_network
        depends_on:
            - postgis

    frontend:
        build:
            context: ./frontend
            dockerfile: Dockerfile
        ports:
            - "80:80"
        volumes:
            - ./frontend:/usr/share/nginx/html/
        networks:
            - zaplechnik_network

    postgis:
        image: 'postgis/postgis:17-3.5-alpine'
        ports:
            - '${FORWARD_DB_PORT:-5432}:5432'
        environment:
            POSTGRES_DB: 'zaplechnik_db'
            POSTGRES_USER: 'vandra'
            POSTGRES_PASSWORD: 'secret'
        volumes:
            - 'pgsql_data:/var/lib/postgresql/data'
        networks:
            - zaplechnik_network

volumes:
    pgsql_data:
        driver: local

networks:
    zaplechnik_network:
        driver: bridge